/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AdsService } from "../ads.service";
import { AdsCreateInput } from "./AdsCreateInput";
import { Ads } from "./Ads";
import { AdsFindManyArgs } from "./AdsFindManyArgs";
import { AdsWhereUniqueInput } from "./AdsWhereUniqueInput";
import { AdsUpdateInput } from "./AdsUpdateInput";
import { CategoriesFindManyArgs } from "../../categories/base/CategoriesFindManyArgs";
import { Categories } from "../../categories/base/Categories";
import { CategoriesWhereUniqueInput } from "../../categories/base/CategoriesWhereUniqueInput";

export class AdsControllerBase {
  constructor(protected readonly service: AdsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ads })
  async createAds(@common.Body() data: AdsCreateInput): Promise<Ads> {
    return await this.service.createAds({
      data: {
        ...data,

        adGroup: data.adGroup
          ? {
              connect: data.adGroup,
            }
          : undefined,
      },
      select: {
        adGroup: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        mediaFile: true,
        startDate: true,
        title: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Ads] })
  @ApiNestedQuery(AdsFindManyArgs)
  async adsItems(@common.Req() request: Request): Promise<Ads[]> {
    const args = plainToClass(AdsFindManyArgs, request.query);
    return this.service.adsItems({
      ...args,
      select: {
        adGroup: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        mediaFile: true,
        startDate: true,
        title: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ads })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ads(@common.Param() params: AdsWhereUniqueInput): Promise<Ads | null> {
    const result = await this.service.ads({
      where: params,
      select: {
        adGroup: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        mediaFile: true,
        startDate: true,
        title: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ads })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAds(
    @common.Param() params: AdsWhereUniqueInput,
    @common.Body() data: AdsUpdateInput
  ): Promise<Ads | null> {
    try {
      return await this.service.updateAds({
        where: params,
        data: {
          ...data,

          adGroup: data.adGroup
            ? {
                connect: data.adGroup,
              }
            : undefined,
        },
        select: {
          adGroup: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          mediaFile: true,
          startDate: true,
          title: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ads })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAds(
    @common.Param() params: AdsWhereUniqueInput
  ): Promise<Ads | null> {
    try {
      return await this.service.deleteAds({
        where: params,
        select: {
          adGroup: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          mediaFile: true,
          startDate: true,
          title: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/categoriesItems")
  @ApiNestedQuery(CategoriesFindManyArgs)
  async findCategoriesItems(
    @common.Req() request: Request,
    @common.Param() params: AdsWhereUniqueInput
  ): Promise<Categories[]> {
    const query = plainToClass(CategoriesFindManyArgs, request.query);
    const results = await this.service.findCategoriesItems(params.id, {
      ...query,
      select: {
        ads: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/categoriesItems")
  async connectCategoriesItems(
    @common.Param() params: AdsWhereUniqueInput,
    @common.Body() body: CategoriesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoriesItems: {
        connect: body,
      },
    };
    await this.service.updateAds({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/categoriesItems")
  async updateCategoriesItems(
    @common.Param() params: AdsWhereUniqueInput,
    @common.Body() body: CategoriesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoriesItems: {
        set: body,
      },
    };
    await this.service.updateAds({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/categoriesItems")
  async disconnectCategoriesItems(
    @common.Param() params: AdsWhereUniqueInput,
    @common.Body() body: CategoriesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoriesItems: {
        disconnect: body,
      },
    };
    await this.service.updateAds({
      where: params,
      data,
      select: { id: true },
    });
  }
}
