/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdGroupsWhereUniqueInput } from "../../adGroups/base/AdGroupsWhereUniqueInput";
import { ValidateNested, IsOptional, IsString, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { CategoriesUpdateManyWithoutAdsItemsInput } from "./CategoriesUpdateManyWithoutAdsItemsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class AdsUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AdGroupsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdGroupsWhereUniqueInput)
  @IsOptional()
  @Field(() => AdGroupsWhereUniqueInput, {
    nullable: true,
  })
  adGroup?: AdGroupsWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CategoriesUpdateManyWithoutAdsItemsInput,
  })
  @ValidateNested()
  @Type(() => CategoriesUpdateManyWithoutAdsItemsInput)
  @IsOptional()
  @Field(() => CategoriesUpdateManyWithoutAdsItemsInput, {
    nullable: true,
  })
  categoriesItems?: CategoriesUpdateManyWithoutAdsItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  mediaFile?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;
}

export { AdsUpdateInput as AdsUpdateInput };
